apiVersion: v1
kind: Service
metadata:
  namespace: experimental-redis-cluster
  name: redis
  labels:
    app: redis
spec:
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: experimental-redis-cluster
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: "redis"
  # same as number of nodes of kind workers. c.f. kind.yml
  # at least 6 nodes required
  replicas: 6
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7
        command:
        - "redis-server"
        - "/usr/local/etc/redis/redis.conf"
        volumeMounts:
        - name: redis-conf
          mountPath: /usr/local/etc/redis
      volumes:
      - name: redis-conf
        configMap:
          name: redis-conf
          items:
          - key: redis.conf
            path: redis.conf
